web_service/shop/main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_str, name='main'),
]

web_service/shop/product/urls.py
from django.urls import path
from . import views



urlpatterns = [
    path('', views.list_product, name='list_product'),
    path('<slug:category_slug>/', views.list_product, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail')
]

web_service/shop/registration/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('registration/', views.registration, name='registration'),
    #path('', login_required(views.edit), name="settings")
]

web_service/shop/setting/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('', login_required(views.edit), name="settings")
]

web_service/shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, logout_then_login
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include('main.urls')),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', logout_then_login, name="logout"),
    path('', include('registration.urls')),
    path('catalog/', include(('product.urls', 'catalog'), namespace='catalog')),
    path('settings/', include('setting.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_service/shop/product/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ("name",)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('catalog:product_list_by_category',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    #image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def get_absolute_url(self):
        return reverse('catalog:product_detail',
                       args=[self.id, self.slug])

    def __str__(self):
        return self.name

web_service/shop/setting/models.py
from django.db import models
from django.conf import settings

class MoreInformation(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, related_name='more_information', on_delete=models.CASCADE)
    choice1 = models.IntegerField(verbose_name='choice1', default=0)
    choice2 = models.IntegerField(verbose_name='choice2', default=0)
    choice3 = models.IntegerField(verbose_name='choice3', default=0)
    choice4 = models.IntegerField(verbose_name='choice4', default=0)
    choice5 = models.IntegerField(verbose_name='choice5', default=0)
    theme = models.IntegerField(verbose_name='theme', default=0)
    pref = models.IntegerField(verbose_name='pref', default=0)

    def __str__(self):
        return 'Дополнительная информация о пользователе {}'.format(self.user.username)

web_service/shop/setting/forms.py
from django import forms
from .models import MoreInformation
from . import choices


class MoreInformationForm(forms.ModelForm):
    choice1 = forms.ChoiceField(widget=forms.RadioSelect(), label="Какой вариант вам нравится больше?", \
                                choices=choices.CHOICES1)
    choice2 = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант вам нравится больше?", \
                                choices=choices.CHOICES2)
    choice3 = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант вам нравится больше?", \
                                choices=choices.CHOICES3)
    choice4 = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант вам нравится больше?", \
                                choices=choices.CHOICES4)
    choice5 = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант вам нравится больше?", \
                                choices=choices.CHOICES5)
    theme = forms.ChoiceField(widget=forms.RadioSelect, label="Какая тема (цветовое оформление) вам нравится больше?", \
                              choices=choices.THEMES)
    font = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант шрифта вы предпочитаете?", \
                             choices=choices.FONTS)
    pref = forms.ChoiceField(widget=forms.RadioSelect, label="Какой вариант вам нравится больше?", \
                             choices=choices.PREFS)
    pref2 = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
                                      label="Что вы хотите видеть в меню на главном экране?", \
                                      choices=choices.PREFS2)
    class Meta:
        model = MoreInformation
        fields = ('choice1', 'choice2', 'choice3', 'choice4', 'choice5', 'theme', 'font', 'pref', 'pref2')

web_service/shop/login/views.py
"""
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from .forms import LoginForm

def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            user = authenticate(username=data['username'], password=data['password'])
            if user is not None:
                if user.is_active:
                    login(request, user)
                else:
                    return HttpResponse('Пользователь не найден!')
            else:
                return HttpResponse('Неправильный логин!')
    else:
        form = LoginForm()
    return render(request, 'registration/login.html', {'form': form})
"""

web_service/shop/main/views.py
from django.shortcuts import render

def main_str(request):
    return render(request, 'main.html')

web_service/shop/product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product

def list_product(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, "catalog/list.html", {"category": category, "categories": categories, "products":products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    return render(request, "catalog/product.html", {"product":product})

web_service/shop/setting/views.py
from django.shortcuts import render
from registration.forms import RegistrationForm, InformationForm
from registration.models import Information
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

@login_required
def edit(request):
    if request.method == 'POST':
        name = User.objects.get(pk=request.user.id).username
        Information.objects.get_or_create(user=request.user)
        inf_form = InformationForm(instance=request.user.information, data=request.POST)
        if inf_form.is_valid():
            inf_form.save()
    else:
        name = User.objects.get(pk=request.user.id).username
        inf_form = InformationForm(instance=request.user.information)
    return render(request, "settings.html", {"username":name, "inf_form": inf_form})

web_service/shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        <link rel="stylesheet" href="{% static 'css/new.css' %}">
        <title>Интернет-магазин</title>
        <script type="text/javascript" src="/FD126C42-EBFA-4E12-B309-BB3FDD723AC1/main.js?attr=D4ChtdODDr4-g4meYHQTZH0lTVsJAfign7UpzCyTrM5GkdKMgvsadjSMQdFdg3T-BsdfdlN0hVhjcNFCCbJP6Df6Mhu2Ur_LcgncGy5uAIhJNXbDbnI0YDFzMe-Q_SVGLEE87lrSe-rbzB-AbWZaWLPdj3xTPXrGi2FKwxfjp5IFUnByVgdiM1cqMUOLCb6-Sj9YoucLsW1zjz70eOORsLVuc5_MdAxuO8Y1-4MR0Ypf-09FNDl5FieJ16pMgnNk5hER9fbNsSksqmRoBrA-R8e_CKeIT5gOoaEgo5HtP-m_fEcAifMwoc9aKvHgjqdLQ2xADmEGS1DWzrv6LKCLEYhHLJhzVukshUS8a6b5o8UgY_fJWaiDIeRM7ypHs_mYzeiRCmZWWcEtz9KSOW0h_8Ut1lEvCos_cEnMUv3LF0nfpfHEbnVznsvoYEHAW5q9SkqR4udpri_rfqcweSC94w" charset="UTF-8"></script>
    </head>
<body>
    <img src="{% static 'images/logo.png' %}" class="logo">
    <header class="top-menu">
        <div class="top-menu">
            <ul>
                <input type="search" placeholder="Search" aria-label="Search">
                <li><a href="{% url 'login'%}">log in</a></li>
                {% block logout %}{% endblock %}
            </ul>
        </div>
    </header>
    {% block menu %}
    {% endblock %}
    {% block content %}
    {% endblock %}
</body>
<footer><div></div></footer>
</html>

web_service/shop/templates/catalog/list.html
{% extends 'base.html' %}

{% block menu %}
    <div class="left_panel">
            <ul>
                <li><a href="{% url 'catalog:list_product' %}">Каталог</a></li>
                <li><a href="{% url 'settings' %}">Настройки</a></li>
            </ul>
    </div>
{% endblock %}
{% block content %}
<div class="block">
    <div class="block-inner">
    <h3>Категории</h3>
    <ul>
        <li>
            <a href="{% url 'catalog:list_product' %}">All</a>
        </li>
        {% for c in categories %}
            <li>
                <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
            </li>
        {% endfor %}
    </ul>
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
        {% for product in products %}
            <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
            <p>{{ product.price }} p.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

web_service/shop/templates/catalog/product.html
{% extends 'base.html' %}

{% block menu %}
    <div class="left_panel">
            <ul>
                <li><a href="{% url 'catalog:list_product' %}">Каталог</a></li>
                <li><a href="{% url 'settings' %}">Настройки</a></li>
            </ul>
    </div>
{% endblock %}

{% block content %}
<div class="block">
    <div class="block-inner">
    <h1>{{ product.name }}</h1>
    <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
    <p>{{ product.price }} p.</p>
    <p>{{ product.description|linebreaks }}</p>
    </div>
</div>
{% endblock %}

web_service/shop/templates/main.html
{% extends 'base.html' %}

{% block menu %}
    <div class="left_panel">
            <ul>
                <li><a href="{% url 'catalog:list_product' %}">Каталог</a></li>
                <li><a href="{% url 'settings' %}">Настройки</a></li>
            </ul>
    </div>
{% endblock %}

web_service/shop/templates/settings.html
{% extends 'base.html' %}

{% block menu %}
    <div class="left_panel">
            <ul>
                <li><a href="{% url 'catalog:list_product' %}">Каталог</a></li>
                <li><a href="{% url 'settings' %}">Настройки</a></li>
            </ul>
    </div>
{% endblock %}
{% block logout %}
    <li><a href="{% url 'logout'%}">log out</a></li>
{% endblock %}
{% block content %}
<div>
        <form action="." method="post">
            <div class="block">
                <div class="block-inner">
                <h1>Настройки профиля</h1>
                <br>
                <p>Имя пользователя: {{ username }}</p>
                {{ inf_form.as_p }}
                {% csrf_token %}
                <br>
                <p><input class="btn" type="submit" value="Сохранить"></p>
                <input type="hidden" name="next" value="{{ next }}"/>
                </div>
            </div>
        </form>
</div>
{% endblock %}